spring.application.name=demo
logging.level.org.springframework=info
management.endpoints.web.exposure.include=*
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.defer-datasource-initialization=true
package com.sb.flatfilereader.config;
import java.util.List;
import org.springframework.batch.core.Job;
import org.springframework.batch.core.Step;
import org.springframework.batch.core.configuration.annotation.EnableBatchProcessing;
import org.springframework.batch.core.configuration.annotation.JobBuilderFactory;
import org.springframework.batch.core.configuration.annotation.StepBuilderFactory;
import org.springframework.batch.core.configuration.annotation.StepScope;
import org.springframework.batch.core.launch.support.RunIdIncrementer;
import org.springframework.batch.item.ItemProcessor;
import org.springframework.batch.item.ItemWriter;
import org.springframework.batch.item.file.MultiResourceItemReader;
import org.springframework.batch.item.file.ResourceAwareItemReaderItemStream;
import org.springframework.batch.item.json.JacksonJsonObjectReader;
import org.springframework.batch.item.json.JsonItemReader;
import org.springframework.batch.item.json.builder.JsonItemReaderBuilder;
import org.springframework.batch.item.support.SynchronizedItemStreamReader;
import org.springframework.batch.item.support.builder.SynchronizedItemStreamReaderBuilder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.io.FileSystemResource;
import org.springframework.core.io.Resource;
import org.springframework.core.task.TaskExecutor;
import org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor;
import org.springframework.stereotype.Component;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
//@Configuration
//@EnableBatchProcessing
//@Component
//@RequiredArgsConstructor
//@Slf4j
public class BatchConfiguration {
	@Autowired
	private JobBuilderFactory jobBuilderFactory;
	@Autowired
	private StepBuilderFactory stepBuilderFactory;
	Resource[] resources = new Resource[]{new FileSystemResource("c:\\data\\combined_file.json"), new FileSystemResource("c:\\data\\combined_file2.json"), new FileSystemResource("c:\\data\\combined_file3.json")};
			
			//new Resource[]{new FileSystemResource("c:\\data\\cat-full-load_dc_Test_1.json"), new FileSystemResource("c:\\data\\cat-full-load_dc_Test_2.json")};
	
	@Bean(name="readJsonFilesJob")
	public Job readJsonFilesJob() {
		return jobBuilderFactory.get("readJsonFilesJob")
				.incrementer(new RunIdIncrementer())            
				.start(readJsonFilesStep())
				.build();
	}
	
	@Bean (name ="categoryJsonReaderSingleLargeFile")
	@StepScope
	public JsonItemReader<ASOCategory> getCategoryJsonItemReader() {
		JsonItemReader<ASOCategory> categoryJsonReader = new JsonItemReader<>();
		/* This code can be used for GCP reading 
		 * Storage storage = StorageApplication.storage(); ReadChannel channel =
		 * storage.reader(catalogConfig.getGcsCategoryBucketName(),
		 * catalogConfig.getGcsCatgeoryFilename()); InputStream inputStream =
		 * Channels.newInputStream(channel); InputStreamResource resource = new
		 * InputStreamResource(inputStream); categoryJsonReader.setResource(resource);
		 */	   
		categoryJsonReader.setResource(resources[0]); // remove this line if using GCP
		categoryJsonReader.setJsonObjectReader(new JacksonJsonObjectReader<>(ASOCategory.class));
	    return categoryJsonReader;
	}
	@Bean
	public Step readJsonFilesStep() {
		return stepBuilderFactory.get("readJsonFilesStep")
				.<ASOCategory, ASOCategory>chunk(10)
				.reader(synchronizedReader())
				.processor(jsonItemProcessor())
				.writer(jsonItemWriter())       
				.taskExecutor(taskExecutor())
				.build();
	}
	
	// For multiple files this can be used
	@Bean
	public MultiResourceItemReader<ASOCategory> multiResourceReader() {
		ResourceAwareItemReaderItemStream<ASOCategory> delegate = new JsonItemReaderBuilder<ASOCategory>()
				.name("delegatedObjReader").jsonObjectReader(new JacksonJsonObjectReader<>(ASOCategory.class)).strict(false)
				.build();
		MultiResourceItemReader<ASOCategory> reader = new MultiResourceItemReader<>();
		reader.setResources(resources);
		reader.setStrict(false);
		reader.setDelegate(delegate);
		return reader;
	}
	
	public SynchronizedItemStreamReader<ASOCategory> synchronizedReader() {
		return new SynchronizedItemStreamReaderBuilder<ASOCategory>()
				   //.delegate(getCategoryJsonItemReader()) // comment this if want to use single resource reader ()
				   .delegate(multiResourceReader()) // uncomment this if need to use multi resource reader 
				.build();
	}
	
	@Bean
	public ItemProcessor<ASOCategory, ASOCategory> jsonItemProcessor() {
		return new ItemProcessor<ASOCategory, ASOCategory>() {
			@Override
			public ASOCategory process(ASOCategory item) throws Exception {
				return item;
			}
		};
	}
	@Bean
	public ItemWriter<ASOCategory> jsonItemWriter() {
		return new ItemWriter<ASOCategory>() {
			@Override
			public void write(List<? extends ASOCategory> items) throws Exception {
				System.out.print("Items that can be written "+items);
			}
		};
	}
	@Bean
	public TaskExecutor taskExecutor() {
		ThreadPoolTaskExecutor taskExecutor = new ThreadPoolTaskExecutor();
		taskExecutor.setCorePoolSize(10);
		taskExecutor.setMaxPoolSize(10);
		taskExecutor.setQueueCapacity(10);
		taskExecutor.afterPropertiesSet();
		return taskExecutor;
	}
}
