version: '3.7'
services:
  sampleproject:
    image: dc99999/mmv2-samplproject:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports: 
      - "8080:8080"
    networks:
      - sampleproject
networks:
  sampleproject:
  